### ISSUE TITLE
CPU ISA level is lower than required

### ISSUE THREAD

**Issue by Plavil** [whrvt/wine-osu-patches#1]
I tried to use wine-osu-spectator-9.16-3 and in console it was said 
CPU ISA level is lower than required, i thought it was because i was using ivybridge (v2) cpu, so i switched my hard drive to another PC with i5 6600 cpu (v3), but issue remained..
Gotta check wine-osu-spectator-9.16-2 to see if it's fixed

Upd. same issue, i guess i'll just compile it from aur repo, good job anyway

**Comment by whrvt** [comment]
This is the issue with attempting to compile portable binaries without using a isolated chroot like [this](https://github.com/NelloKudo/WineBuilder) or a docker container etc. when your system libraries are compiled for a different architecture level. A few of Wine's components link in static libraries, which for my particular system are mostly taken from the `[cachyos-znver4*]` repositories.
 
I recently thought that I had worked around this issue by specifying a plain x86-64 `libgcc.a` to the linker, but unfortunately there are still many occurrences of AVX512 instructions in the package (5638 to be exact). It's inconvenient, but the binaries are not really the point of this repository anyways, AUR helpers make it very easy to build it yourself with native optimizations.

I'll leave this issue open so that people know that I'm aware of it, but I'm not going to place a very high priority on fixing it.

**Comment by whrvt** [comment]
Never mind that, rebuilt the packages in a virtual machine and uploaded them. Will do this for future releases.
